name: atsSignTeleport
main: eu.andret.ats.signteleport.SignTeleportPlugin
version: 0.2.1
description: The plugin that allows to create signs that teleport
api-version: 1.17
author: Andret2344
website: https://www.spigotmc.org/resources/ats-andret-tools-system-sign-teleport-place-a-sign-teleporting-clicking-player.104918/
libraries:
  - org.jetbrains:annotations:26.1.0

commands:
  signteleport:
    description: SignTeleport commands
    usage: /signteleport reload
    permission: ats.signteleport.reload

permissions:
  ats.signteleport.*:
    description: Grants all permissions for SignTeleport
    children:
      ats.signteleport.use: true
      ats.signteleport.create: true
      ats.signteleport.break: true
      ats.signteleport.reload: true
  ats.signteleport.use:
    description: Allows using teleport signs
    default: true
  ats.signteleport.create:
    description: Allows creating teleport signs
    default: op
  ats.signteleport.break:
    description: Allows breaking teleport signs
    default: op
  ats.signteleport.reload:
    description: Allows reloading the SignTeleport configuration
    default: op
